CREATE DATABASE GESTION_EVENTOS;
USE GESTION_EVENTOS;

CREATE TABLE ORGANIZADORES(
ID_ORGANIZADOR INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE_ORGANIZADOR VARCHAR(50) NOT NULL,
CORREO VARCHAR(50) UNIQUE NOT NULL,
FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CATEGORIA(
ID_CATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE_CATEGORIA VARCHAR(50) NOT NULL
);

CREATE TABLE UBICACIONES(
ID_UBICACION INT AUTO_INCREMENT PRIMARY KEY,
TIPO ENUM('presencial', 'online') NOT NULL,
DIRECCION VARCHAR(255),
ENLACE_VIRTUAL VARCHAR(255)
);

CREATE TABLE EVENTOS(
ID_EVENTO INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE_EVENTO VARCHAR(100) NOT NULL, 
FECHA_EVENTO DATETIME NOT NULL,
UBICACION_ID INT,
CATEGORIA_ID INT,
ORGANIZADOR_ID INT,
ESTADO ENUM('activo', 'cancelado') NOT NULL,
FOREIGN KEY (UBICACION_ID) REFERENCES UBICACIONES(ID_UBICACION),
FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIAS(ID_CATEGORIA),
FOREIGN KEY (ORGANIZADOR_ID) REFERENCES ORGANIZADORES(ID_ORGANIZADOR)
);

CREATE TABLE USUARIOS(
ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE_USUARIO VARCHAR(100) NOT NULL,
CORREO_USUARIO VARCHAR(100) UNIQUE NOT NULL,
FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE INSCRIPCIONES(
ID_INCRIPCION INT AUTO_INCREMENT PRIMARY KEY,
USUARIO_ID INT,
EVENTO_ID INT,
FECHA_INSCRIPCION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ESTADO_INSCRIPCION ENUM('activo', 'cancelado'),
FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID_USUARIO),
FOREIGN KEY (EVENTO_ID) REFERENCES EVENTOS(ID_EVENTO)
);